### ISSUE TITLE
Application crashes when calling ThermalPrinter.requestPermissions 

### ISSUE THREAD

**Issue by WingsDevelopment** [paystory-de/thermal-printer-cordova-plugin#46]
Here is my current code:

```
"use client"
import React, { useRef, useState } from "react"
import { Printer, ThermalPrinterPlugin } from "thermal-printer-cordova-plugin/src"
declare let ThermalPrinter: ThermalPrinterPlugin

export const PrintableOrder = ({ order }) => {
	const [usPrinters, setUsPrinters] = useState<Printer[]>([])

	const handlePrint = () => {
		const formattedText =
			'[C]<u><font size="big">ORDER N°045</font></u>\n' +
			"[L]\n" +
			"[C]================================\n" +
			"[L]\n" +
			"[L]<b>BEAUTIFUL SHIRT</b>[R]9.99e\n" +
			"[L]  + Size : S\n" +
			"[L]\n" +
			"[L]<b>AWESOME HAT</b>[R]24.99e\n" +
			"[L]  + Size : 57/58\n" +
			"[L]\n" +
			"[C]--------------------------------\n" +
			"[R]TOTAL PRICE :[R]34.98e\n" +
			"[R]TAX :[R]4.23e\n" +
			"[L]\n" +
			"[C]================================\n" +
			"[L]\n" +
			"[L]Raymond DUPONT\n" +
			"[L]5 rue des girafes\n" +
			"[L]31547 PERPETES\n" +
			"[L]Tel : +33801201456\n"

		ThermalPrinter.listPrinters(
			{ type: "bluetooth" },
			(printers) => {
				if (printers.length > 0) {
					setUsPrinters(printers)
					ThermalPrinter.requestPermissions(
						{ type: "bluetooth", id: printers[0].address ?? "SimulatePrinter" },
						function (result) {
							ThermalPrinter.printFormattedTextAndCut(
								{
									type: "bluetooth",
									id: printers[0].address ?? "SimulatePrinter",
									text: formattedText,
								},
								() => {
									alert("Successfully printed!")
								},
								(error) => {
									alert(error)
								}
							)
						},
						function (error) {
							console.log(error)
						}
					)
				} else {
					alert("no printers;")
				}
			},
			(e) => alert(e)
		)
	}

	return (
		<div>
			this is some kind of a test kekw :/
			<button
				style={{
					margin: "5px",
					border: "black",
					color: "yellow",
				}}
				onClick={handlePrint}
			>
				Print Order 1
			</button>
			<pre>{JSON.stringify(usPrinters, null, 2)}</pre>
		</div>
	)
}

```

here is error... 

FATAL EXCEPTION: pool-7-thread-1
                                                                                                    Process: rs.deliverko, PID: 3461
                                                                                                    java.lang.ClassCastException: com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection cannot be cast to com.dantsu.escposprinter.connection.usb.UsbConnection
                                                                                                    	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin.requestUSBPermissions(ThermalPrinterCordovaPlugin.java:96)
                                                                                                    	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin.lambda$execute$0$de-paystory-thermal_printer-ThermalPrinterCordovaPlugin(ThermalPrinterCordovaPlugin.java:60)
                                                                                                    	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin$$ExternalSyntheticLambda0.run(Unknown Source:8)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)

Any idea why?

I have permissions edited in my AndroidManifest.xml:
```

    <!-- Permissions -->
    <uses-feature android:name="android.hardware.usb.host" />
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH" />
    <uses-permission android:maxSdkVersion="30" android:name="android.permission.BLUETOOTH_ADMIN" />
    <uses-permission android:name="android.permission.BLUETOOTH_PRIVILEGED"/>
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" />
    
    <uses-permission android:name="android.permission.INTERNET" />
```

when running without requestPermissions I get :
java.io.IOException: Connection refused
2023-08-13 16:36:23.624  1277-1648  System.err              rs.deliverko                         W  	at android.net.LocalSocketImpl.connectLocal(Native Method)
2023-08-13 16:36:23.624  1277-1648  System.err              rs.deliverko                         W  	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:292)
2023-08-13 16:36:23.624  1277-1648  System.err              rs.deliverko                         W  	at android.net.LocalSocket.connect(LocalSocket.java:145)
2023-08-13 16:36:23.624  1277-1648  System.err              rs.deliverko                         W  	at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:367)
2023-08-13 16:36:23.625  1277-1648  System.err              rs.deliverko                         W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:66)
2023-08-13 16:36:23.625  1277-1648  System.err              rs.deliverko                         W  	at com.dantsu.escposprinter.connection.bluetooth.BluetoothConnection.connect(BluetoothConnection.java:14)
2023-08-13 16:36:23.625  1277-1648  System.err              rs.deliverko                         W  	at com.dantsu.escposprinter.EscPosPrinterCommands.connect(EscPosPrinterCommands.java:223)
2023-08-13 16:36:23.625  1277-1648  System.err              rs.deliverko                         W  	at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:54)
2023-08-13 16:36:23.626  1277-1648  System.err              rs.deliverko                         W  	at com.dantsu.escposprinter.EscPosPrinter.<init>(EscPosPrinter.java:40)
2023-08-13 16:36:23.626  1277-1648  System.err              rs.deliverko                         W  	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin.getPrinter(ThermalPrinterCordovaPlugin.java:316)
2023-08-13 16:36:23.626  1277-1648  System.err              rs.deliverko                         W  	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin.printFormattedText(ThermalPrinterCordovaPlugin.java:197)
2023-08-13 16:36:23.626  1277-1648  System.err              rs.deliverko                         W  	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin.lambda$execute$0$de-paystory-thermal_printer-ThermalPrinterCordovaPlugin(ThermalPrinterCordovaPlugin.java:54)
2023-08-13 16:36:23.627  1277-1648  System.err              rs.deliverko                         W  	at de.paystory.thermal_printer.ThermalPrinterCordovaPlugin$$ExternalSyntheticLambda0.run(Unknown Source:8)
2023-08-13 16:36:23.627  1277-1648  System.err              rs.deliverko                         W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2023-08-13 16:36:23.627  1277-1648  System.err              rs.deliverko                         W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2023-08-13 16:36:23.628  1277-1648  System.err              rs.deliverko                         W  	at java.lang.Thread.run(Thread.java:764)
2023-08-13 16:36:24.302  1277-1277  Choreographer           rs.deliverko                         I  Skipped 36 frames!  The application may be doing too much work on its main thread.
2023-08-13 16:36:24.524  1277-1374  Adreno-EGL              rs.deliverko                         W  <qeglDrvAPI_eglGetConfigAttrib:612>: EGL_BAD_ATTRIBUTE
2023-08-13 16:36:26.251  1277-1374  Adreno-ES20             rs.deliverko                         W  <core_glFinish:34>: glFinish skipped: 0
2023-08-13 16:36:26.262  1277-1374  Adreno-ES20             rs.deliverko                         W  <core_glFinish:34>: glFinish skipped: 0
2023

**Comment by WingsDevelopment** [comment]
Okay turns out that I shouln't ask for permissions when using bluetooth device, please correct me if im wrong...
But when I just call printFormattedText I get: java.io.IOException: Connection refused.

I've create empty project and I am able to print inside that project. but when using same code, same android manifest file, in my real aplication i get java.io.IOException: Connection refused... Am I missing something ? What could cause this ?..

Since i know that printing code is okay and android manifest file is okay, is there something else that could cause this?

**Comment by WingsDevelopment** [comment]
Okay aperently it was a problem with device, because after some testing turns out that with same code sometimes works, sometimes doesn't work.... 
If someone is looking for example of working code, you can try with mine, but remove requestPermissions call, and i don't know if you are using chinese printer, keep trying, restart device, restart bluetooth etc...
